PRODUCT-ENDPOINT setup
GFG/seller-center-sdk-go pull request #2
Opened 2018-07-13 10:31 UTC by andreasph

2018-07-23 12:24 UTC, miladsssh requested changes

2018-07-23 12:24 UTC, miladsssh commented on resource/product.go
> +	err = json.Unmarshal(rawBrands, &brands)
I think it would be more consistent if we face some errors just return an empty model.Brands{}, just need to add one more check for err

2018-07-23 12:24 UTC, miladsssh commented on resource/product.go
> +	err = json.Unmarshal(rawCategories, &categories)
like above

2018-07-23 12:24 UTC, miladsssh commented on resource/product.go
> +	err = json.Unmarshal(rawBody, &attributes)
like above

2018-07-23 12:24 UTC, miladsssh commented on resource/product.go
> +	if err := json.Unmarshal(rawBody, &products); nil != err {
** you have already checked here

2018-07-23 12:24 UTC, miladsssh commented on resource/order.go
> +func (oe OrderResource) GetOrders(
please change the variable to "or" instead of "oe" i think oe is for OrderEndpoing

2018-07-23 12:24 UTC, miladsssh commented on resource/order.go
> +func (oe OrderResource) GetOrder(orderId int) (model.Order, error) {
"or" instead of "oe"

2018-07-23 12:24 UTC, miladsssh commented on resource/order.go
> +	if len(orders.Orders) == 1 {
just for the sake of consistency check if len is 0 then return model.Order{}, errors.New("cannot find order") otherwise return orders.Orders[0], nil

2018-07-23 12:24 UTC, miladsssh commented on resource/order.go
> +func (oe OrderResource) GetOrderItems(orderId int) (model.OrderItems, error) {
"or" instead of "oe"

2018-07-23 12:24 UTC, miladsssh commented on resource/order.go
> +	err = json.Unmarshal(rawBody, &orderItems)
like the other comments please check err at first and if is nil return empty model.OrderItems{}

2018-07-23 12:24 UTC, miladsssh commented on resource/order.go
> +func (oe OrderResource) GetDocument(orderItemIds []int, documentType model.DocumentType) (model.Document, error) {
"or" instead of "oe"

2018-07-23 12:24 UTC, miladsssh commented on resource/order.go
>  	err = json.Unmarshal(rawDocument, &document)
please check err before

2018-07-23 12:24 UTC, miladsssh commented on resource/order.go
> +func (oe OrderResource) SetStatusToCanceled(orderItemId int, reason string, reasonDetail string) (bool, error) {
if you like find and replace "oe" to "or"

2018-07-23 12:25 UTC, miladsssh commented on example/order.go
>  		dumpOder(order, logger)
dumpOrder

2018-07-23 12:26 UTC, miladsssh commented on example/order.go
>  func dumpOderItem(orderItem model.OrderItem, logger *log.Logger) {
please check it everywhere

2018-07-23 14:37 UTC, miladsssh approved these changes

2018-07-24 07:10 UTC, iru-b commented on resource/product.go
> +package resource
I suggest to split this file into 2-3 smaller files. It will be just more easy to handle.

2018-07-24 09:40 UTC, nicolopignarocket approved these changes

2018-07-24 10:12 UTC, iru-b requested changes

2018-07-24 10:12 UTC, iru-b commented on example/product.go
> +	products, err := productResource.GetProducts(
13 parameters is a really long signature - maybe we can create a ticket to rework this in a next iteration

2018-07-24 10:12 UTC, iru-b commented on model/base_test.go
> +	if err := json.Unmarshal(j, &c); nil != err {
(I do not like this one letter variables - but I know it is golang style - no change requested)

2018-07-24 10:12 UTC, ikuegelgen commented on resource/product_getters.go
> +	return products, err
err must be nil

2018-07-24 10:12 UTC, ikuegelgen commented on resource/product_manipulation.go
> +	return "", errors.New(strings.Join(messages, "\n"))
IMO it would be better to return the structured warning e. g. as `[]warning`

2018-07-24 11:10 UTC, iru-b requested changes
2 comments, and needs to be rebased with master.
Please also simplify the error handling as in https://github.com/GFG/seller-center-sdk-go/commit/b2111e84dda09378268f7c65cb91f347cf13803e#diff-d0a27cec2a40ed300fc0c744d63f6f07

2018-07-24 11:10 UTC, ikuegelgen commented on resource/product_getters.go
> +func (pr ProductResource) GetProducts(
what about passing one struct like `func (pr ProductResource) GetProducts(productsFilter ProductsFilter)`?

2018-07-24 13:33 UTC, iru-b approved these changes

2018-07-24 13:34 UTC, merged